# Generated by Django 3.0.6 on 2020-05-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias de marca',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.ImageField(default='clients/logo_default.jpg', upload_to='clients/')),
                ('banner', models.ImageField(default='clients/logo_default.jpg', upload_to='clients/')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('brand_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.CategoryBrand')),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
    ]
