# Generated by Django 2.2.3 on 2019-07-29 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.ImageField(default='clients/logo_default.jpg', upload_to='clients/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='CategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Categorias de marca',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Categorias de producto',
            },
        ),
        migrations.CreateModel(
            name='UserBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('reference', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='clients/logo_default.jpg', upload_to='clients/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Brand')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.CategoryProduct')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(default='products/image_default.jpg', upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Product')),
            ],
        ),
        migrations.CreateModel(
            name='DetailImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('marker_x', models.FloatField()),
                ('marker_y', models.FloatField()),
                ('image_check', models.ImageField(default='products/details/image_default.jpg', upload_to='products/details')),
                ('image_fail', models.ImageField(default='products/details/image_default.jpg', upload_to='products/details')),
                ('image_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ImageProduct')),
            ],
            options={
                'verbose_name_plural': 'Marcadores de Detalles',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.CategoryBrand'),
        ),
    ]
