# Generated by Django 2.2.1 on 2019-06-02 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('reference', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.CategoryProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='products/image_default.jpg', upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Product')),
            ],
        ),
        migrations.CreateModel(
            name='DetailImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image_check', models.ImageField(default='products/details/image_default.jpg', upload_to='products/details')),
                ('image_fail', models.ImageField(default='products/details/image_default.jpg', upload_to='products/details')),
                ('image_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ImageProduct')),
            ],
        ),
    ]
