# Generated by Django 2.2.1 on 2019-06-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_categoryproduct_detailimageproduct_imageproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduct',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
