# Generated by Django 2.2.3 on 2019-07-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190729_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='products/image_default.jpg', null=True, upload_to='products/'),
        ),
    ]
