# Generated by Django 2.2.1 on 2019-06-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_imageproduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailimageproduct',
            name='marker_x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailimageproduct',
            name='marker_y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
