# Generated by Django 2.2.3 on 2019-07-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users/default-avatar.png', null=True, upload_to='users/'),
        ),
    ]
