# Generated by Django 2.2.4 on 2019-08-19 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190729_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movil',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Operativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('expiration', models.DateField()),
                ('first_login', models.DateField()),
                ('last_login', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.User')),
            ],
        ),
    ]
