# Generated by Django 2.2.1 on 2019-07-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190602_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='categorybrand',
            options={'verbose_name_plural': 'Categorias de marca'},
        ),
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name_plural': 'Categorias de producto'},
        ),
        migrations.AlterModelOptions(
            name='detailimageproduct',
            options={'verbose_name_plural': 'Marcadores de Detalles'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
