# Generated by Django 2.2.4 on 2019-08-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190819_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operativo',
            name='expiration',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='operativo',
            name='first_login',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='operativo',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
