# Generated by Django 2.2.1 on 2019-07-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190706_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='clients/logo_default.jpg', upload_to='clients/'),
        ),
    ]
