# Generated by Django 2.2.4 on 2019-08-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190820_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
