# Generated by Django 2.2.1 on 2019-09-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_operativo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='banner',
            field=models.ImageField(default='clients/logo_default.jpg', upload_to='clients/'),
        ),
    ]
