# Generated by Django 2.2.1 on 2019-10-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_brand_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetailCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_check', models.ImageField(default='products/details/image_default.jpg', upload_to='products/details')),
                ('type_image', models.CharField(choices=[('1', 'Imagen Correcta'), ('2', 'Imagen Incorrecta')], default='', max_length=15)),
            ],
        ),
    ]
