# Generated by Django 2.2.1 on 2019-10-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_imagedetailcompare'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetailcompare',
            name='detail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.DetailImageProduct'),
        ),
    ]
