# Generated by Django 2.2.1 on 2019-10-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20191007_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativo',
            name='activation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
