# Generated by Django 2.2.1 on 2019-10-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_operativo_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operativo',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
