# Generated by Django 2.2.1 on 2019-10-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20191009_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativo',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operativo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
