# Generated by Django 2.2.1 on 2019-10-10 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20191009_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperativoBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_prodcut', models.BooleanField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Brand')),
                ('operativo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Operativo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Product')),
            ],
        ),
    ]
