# Generated by Django 2.2.1 on 2019-10-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_operativobrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativo',
            name='brandsList',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='operativo',
            name='productList',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
