# Generated by Django 2.2.1 on 2019-10-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20191009_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
