# Generated by Django 2.2.1 on 2019-11-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_operativo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetailcompare',
            name='image_fail',
            field=models.ImageField(default='products/details/image_default.jpg', upload_to='products/details'),
        ),
    ]
