# Generated by Django 2.2.1 on 2019-11-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_imagedetailcompare_image_fail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedetailcompare',
            name='image_check',
            field=models.ImageField(blank=True, upload_to='products/details'),
        ),
        migrations.AlterField(
            model_name='imagedetailcompare',
            name='image_fail',
            field=models.ImageField(blank=True, upload_to='products/details'),
        ),
    ]
