# Generated by Django 2.2.1 on 2019-11-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20191105_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedetailcompare',
            name='type_image',
        ),
    ]
