# Generated by Django 2.2.1 on 2019-11-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_imagedetailcompare_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativo',
            name='token_chat',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
