# Generated by Django 2.2.1 on 2020-01-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_operativo_token_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operativo',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
