# Generated by Django 3.0.5 on 2020-04-13 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20200407_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailimageproduct',
            name='image_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ImageProduct'),
        ),
        migrations.AlterField(
            model_name='imagedetailcompare',
            name='detail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.DetailImageProduct'),
        ),
    ]
