# Generated by Django 3.0.5 on 2020-04-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20200412_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativo',
            name='connections',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
