# Generated by Django 2.2.1 on 2020-05-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20200516_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operativoconnection',
            name='name_user',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
