# Generated by Django 2.2.1 on 2020-05-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_operativoconnection_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user_token',
            field=models.BooleanField(default=False),
        ),
    ]
