# Generated by Django 2.2.1 on 2020-05-17 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_user_is_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operativoconnection',
            name='crypto',
        ),
        migrations.AddField(
            model_name='operativoconnection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.User'),
        ),
    ]
