# Generated by Django 3.0.6 on 2020-05-22 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20200516_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativoconnection',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operativoconnection',
            name='user',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.User'),
        ),
    ]
