# Generated by Django 3.0.6 on 2020-05-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('backend', '0034_auto_20200522_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operativobrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brands.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brands.Brand'),
        ),
        migrations.AlterField(
            model_name='user',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='brands.Brand'),
        ),
        migrations.AlterField(
            model_name='userbrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brands.Brand'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='CategoryBrand',
        ),
    ]
