# Generated by Django 2.2.1 on 2020-09-01 22:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20200522_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativo',
            name='close_observation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagedetailcompare',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operativoconnection',
            name='user',
            field=models.ForeignKey(blank=True,  null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='backend.Brand'),
        ),
    ]
